#ifndef KSM_DBSMSG_H
#define KSM_DBSMSG_H

/* This file is generated by a perl script - it should not be edited */

#define DBS_MIN_VALUE (DBS_BASE)
#define DBS_MAX_VALUE (DBS_BASE + 15)
#define DBS_ARRAY_SIZE (16)

static const char* d_messages[] = {
	"ERROR: failed to enable autocommit - %s",
	"ERROR: buffer overflow in %s",
	"ERROR: unable to connect to database - %s",
	"ERROR: could not initialize handle to database",
	"ERROR: invalid arguments to %s",
	"ERROR: invalid index of %d, maximum index is %d",
	"ERROR: no result obtained from query where one was expected",
	"ERROR: unable to get ID of last inserted row - no such row created?",
	"ERROR: not connected to the database",
	"INFO: not connected to the database",
	"ERROR: expected integer result from query, but obtained '%s' instead",
	"ERROR: error executing SQL - %s",
	"ERROR: unable to allocate prepared statement structure",
	"ERROR: unable to create prepared statement - %s",
	"WARNING: query '%s' returned too many rows, excess ignored",
	"ERROR: unexpected result from executing SQL statement '%s'",

/* ... and null-terminate the array to be on the safe side */

	NULL
};
#endif /* KSM_DBSMSG_H */
